BookstoreWebApp/Controllers/BooksController.cs
using BookstoreProjectData.Entities;
using BookstoreProjectData;
using BookstoreWebApp.Models.Events;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BookstoreWebApp.Models.Books;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using BookstoreWebApp.Models.Reviews;

namespace BookstoreWebApp.Controllers
{
    public class BooksController : Controller
    {
        private readonly BookstoreContext context;
        public BooksController(BookstoreContext _context)
        {
            context = _context;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var books = await context.Books.Select(b => new BooksIndexViewModel
            {
                Id = b.Id,
                Title = b.Title,
                Price = b.Price,
                CoverImageUrl = b.CoverImageUrl,
                AuthorName = b.Author.FullName,
                PromotionPercent = b.Promotion.Percent

            }).ToListAsync();

            return View(books);
           
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var authors = await context.Authors.OrderBy(a => a.FullName).ToListAsync();
            ViewBag.Authors = new SelectList(authors, "Id", "FullName");

            var genres = await context.Genres.OrderBy(a => a.Name).ToListAsync();
            ViewBag.Genres = new SelectList(genres, "Id", "Name");

            var promotions = await context.Promotions.OrderBy(a => a.Percent).ToListAsync();
            ViewBag.Promotions = new SelectList(promotions, "Id", "Percent");

            return View(new BooksCreateViewModel()); ; 
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(BooksCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var authors = await context.Authors.OrderBy(a => a.FullName).ToListAsync();
                ViewBag.Authors = new SelectList(authors, "Id", "FullName");

                var genres = await context.Genres.OrderBy(a => a.Name).ToListAsync();
                ViewBag.Genres = new SelectList(genres, "Id", "Name");

                var promotions = await context.Promotions.OrderBy(a => a.Percent).ToListAsync();
                ViewBag.Promotions = new SelectList(promotions, "Id", "Percent");

                return View(model);
            }

            var book = new Book
            {
                Id = Guid.NewGuid(),
                Title = model.Title,
                Price = model.Price,
                CoverImageUrl = model.CoverImageUrl,
                Synopsis = model.Synopsis,
                AuthorId = model.AuthorId,
                GenreId = model.GenreId,
                PromotionId = model.PromotionId
            };

            await context.Books.AddAsync(book);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var model = await context.Books
                .Where(b => b.Id == id)
                .Select(b => new BooksDeleteViewModel
                {
                    Id = b.Id
                })
                .FirstOrDefaultAsync();

            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Delete(BooksDeleteViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var book = await context.Books.FindAsync(model.Id);
            if (book == null) { return NotFound(); }

            context.Books.Remove(book);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var book = await context.Books.FindAsync(id);
            if (book == null) { return NotFound(); }

            var model = new BooksEditViewModel
            {
                Id = book.Id,
                Title = book.Title,
                Price = book.Price,
                CoverImageUrl = book.CoverImageUrl,
                Synopsis = book.Synopsis,
                AuthorId = book.AuthorId,
                GenreId = book.GenreId,
                PromotionId = book.PromotionId
            };

            var authors = await context.Authors.OrderBy(a => a.FullName).ToListAsync();
            ViewBag.Authors = new SelectList(authors, "Id", "FullName");

            var genres = await context.Genres.OrderBy(a => a.Name).ToListAsync();
            ViewBag.Genres = new SelectList(genres, "Id", "Name");

            var promotions = await context.Promotions.OrderBy(a => a.Percent).ToListAsync();
            ViewBag.Promotions = new SelectList(promotions, "Id", "Percent");

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Edit(BooksEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                var authors = await context.Authors.OrderBy(a => a.FullName).ToListAsync();
                ViewBag.Authors = new SelectList(authors, "Id", "FullName");

                var genres = await context.Genres.OrderBy(a => a.Name).ToListAsync();
                ViewBag.Genres = new SelectList(genres, "Id", "Name");

                var promotions = await context.Promotions.OrderBy(a => a.Percent).ToListAsync();
                ViewBag.Promotions = new SelectList(promotions, "Id", "Percent");

                return View(model);
            }

            var book = await context.Books.FindAsync(model.Id);
            if (book == null) { return NotFound(); }

            book.Title = model.Title;
            book.Price = model.Price;
            book.CoverImageUrl = model.CoverImageUrl;
            book.Synopsis = model.Synopsis;
            book.AuthorId = model.AuthorId;
            book.GenreId = model.GenreId;
            book.PromotionId = model.PromotionId;

            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var book = await context.Books.Where(book => book.Id == id).Select(book => new BooksDetailsViewModel
            {
                Id = book.Id,
                Title = book.Title,
                Synopsis = book.Synopsis,
                GenreName = book.Genre.Name,
                Reviews = book.Reviews.Select(r=> new ReviewIndexViewModel
                {
                    Id = r.Id, Username = r.User.UserName, Text = r.Text, DateAndTime = r.DateAndTime, BookId = book.Id
                }).ToList()
            }).FirstOrDefaultAsync();

            if (book == null) { return NotFound(); };
            return View(book);
        }
    }
}

BookstoreWebApp/Controllers/EventsController.cs
//using AspNetCore;
using BookstoreProjectData;
using BookstoreProjectData.Entities;
using BookstoreWebApp.Models.Books;
using BookstoreWebApp.Models.Events;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Infrastructure;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualBasic;

namespace BookstoreWebApp.Controllers
{
    public class EventsController : Controller
    {
        private readonly BookstoreContext context;
        public EventsController(BookstoreContext _context)
        {
            context = _context;
        }

        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var events = await context.Events.Select(o => new EventsIndexViewModel
            {
                Id = o.Id,
                Name = o.Name,
                DateAndTime = o.DateAndTime,
                AuthorId = o.AuthorId
            }).ToListAsync();
            
            return View(events);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var authors = await context.Authors.OrderBy(a=>a.Id).ToListAsync();
            ViewBag.Authors = new SelectList(authors, "Id", "FullName");

            return View(new EventsCreateViewModel()); //or authors?
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Create(EventsCreateViewModel model)
        {
            if(!ModelState.IsValid)
            {
                return View(model);
            }

            var eventt = new Event
            {
                Id = Guid.NewGuid(),
                Name = model.Name,
                DateAndTime = model.DateAndTime,
                AuthorId = model.AuthorId
            };

            await context.Events.AddAsync(eventt);
            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var model = await context.Events
                .Where(e => e.Id == id)
                .Select(b => new EventsDeleteViewModel
                {
                    Id = b.Id
                })
                .FirstOrDefaultAsync();

            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }
        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> Delete(EventsDeleteViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var eventt = await context.Events.FindAsync(model.Id);
            if(eventt == null) { return NotFound(); }
            
            context.Events.Remove(eventt);
            await context.SaveChangesAsync();
            return RedirectToAction("Index"); 
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var eventt = await context.Events.FindAsync(id);
            if (eventt == null) { return NotFound(); }

            var model = new EventsIndexViewModel
            {
                Id = eventt.Id,
                Name = eventt.Name,
                DateAndTime = eventt.DateAndTime,
                AuthorId = eventt.AuthorId
            };

            return View(model); 
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult>Edit(EventsIndexViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var eventt = await context.Events.FindAsync(model.Id);
            if (eventt == null) { return NotFound(); }

            eventt.Name = model.Name;
            eventt.DateAndTime = model.DateAndTime;
            eventt.AuthorId = model.AuthorId;

            await context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
    }

} 

BookstoreWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookstoreWebApp</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/templatemo-style.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookstoreWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">

                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/img/booklogo.png" alt="Logo" class="tm-site-logo" width="50" height="50">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                        </li>
                    </ul>
                    <span class="navbar-text"> <partial name="_LoginPartial" /> </span>
                </div>
            </div>
        </nav>
    </header>
    <header style="display:none;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookstoreWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Privacy">Books</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <header style="display:none">
        <div class="tm-top-header">
            <div class="container">
                <div class="row">
                    <div class="tm-top-header-inner">
                        <div class="tm-logo-container">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                <img src="~/img/booklogo.png" alt="Logo" class="tm-site-logo" width="50" height="50">
                            </a>

                            
                            <h1 class="tm-site-name tm-handwriting-font">Pink Sunrise</h1>
                        </div>
                        <div class="mobile-menu-icon">
                            <i class="fa fa-bars"></i>
                        </div>
                        <nav class="tm-nav">
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Books</a>
                                </li>
                            </ul>
                        </nav>
                        <partial name="_LoginPartial" />

                    </div>
                </div>
            </div>
        </div>
    </header>

    @if (TempData["SuccessMessage"] != null)
    {
        <div>
            <div class="alert alert-success alert-dismissible fade show">
                @TempData["SuccessMessage"]
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        </div>
    }
    @if (TempData["ErrorMessage"] != null)
    {
        <div>
            <div class="alert alert-danger alert-dismissible fade show">
                @TempData["ErrorMessage"]
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        </div>
    }
    @if (TempData["WarningMessage"] != null)
    {
        <div>
            <div class="alert alert-warning alert-dismissible fade show">
                @TempData["WarningMessage"]
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        </div>
    }

    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>
        <div class="tm-black-bg">
            <div class="container">
                <div class="row margin-bottom-60">
                    <nav class="col-lg-3 col-md-3 tm-footer-nav tm-footer-div">
                        <h3 class="tm-footer-div-title">Main Menu</h3>
                        <ul>
                            <li><a href="#">Home</a></li>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Directory</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Our Services</a></li>
                        </ul>
                    </nav>
                    <div class="col-lg-5 col-md-5 tm-footer-div">
                        <h3 class="tm-footer-div-title">About Us</h3>
                        <p class="margin-top-15">Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante, dapibus in, viverra quis, feugiat a, tellus. Phasellus viverra nulla ut metus varius laoreet.</p>
                        <p class="margin-top-15">Nam quam nunc, blandit vel, luctus pulvinar, hendrerit id, lorem. Maecenas nec odio et ante tincidunt tempus. Donec vitae sapien ut libero venenatis faucibus.</p>
                    </div>
                    <div class="col-lg-4 col-md-4 tm-footer-div">
                        <h3 class="tm-footer-div-title">Get Social</h3>
                        <p>Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. Aliquam lorem ante.</p>
                        <div class="tm-social-icons-container">
                            <a href="#" class="tm-social-icon"><i class="fa fa-facebook"></i></a>
                            <a href="#" class="tm-social-icon"><i class="fa fa-twitter"></i></a>
                            <a href="#" class="tm-social-icon"><i class="fa fa-linkedin"></i></a>
                            <a href="#" class="tm-social-icon"><i class="fa fa-youtube"></i></a>
                            <a href="#" class="tm-social-icon"><i class="fa fa-behance"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div>
            <div class="container">
                <div class="row tm-copyright">
                    <p class="col-lg-12 small copyright-text text-center">Copyright &copy; 2026 <a href="https://github.com/anitsirk66" target="_blank">Kristina Stoyanova</a></p>
                    
                </div>
            </div>
        </div>
    </footer> <!-- Footer content-->
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/templatemo-script.js"></script>
    <script src="~/js/jquery-1.11.2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>